export const Users = [
  {
    _id: 1,
    profileImg: '/assets/person-1.jpg',
    username: 'layla kane',
  },
  {
    _id: 2,
    profileImg: '/assets/person-2.jpg',
    username: 'Jane mont',
  },
  {
    _id: 3,
    profileImg: '/assets/person-3.jpg',
    username: 'Alex Durden',
  },
  {
    _id: 4,
    profileImg: '/assets/person-4.jpg',
    username: 'dave mathews',
  },
  {
    _id: 5,
    profileImg: '/assets/person-5.jpg',
    username: 'Dora Hawks',
  },
  {
    _id: 6,
    profileImg: '/assets/person-6.jpg',
    username: 'brad daymon',
  },
  {
    _id: 7,
    profileImg: '/assets/person-7.jpg',
    username: 'marita steward',
  },
  {
    _id: 8,
    profileImg: '/assets/person-8.jpg',
    username: ' Travis Bennett',
  },
  {
    _id: 9,
    profileImg: '/assets/person-9.jpg',
    username: 'Shirley thomas',
  },
  {
    _id: 10,
    profileImg: '/assets/person-10.jpg',
    username: 'scarlet aniston',
  },
  {
    _id: 11,
    profileImg: '/assets/person-11.jpg',
    username: 'nathalie johanson',
  },
];

export const Posts = [
  {
    id: 1,
    desc: 'Love For All, Hatred For None.',
    photo: '/assets/peace-post.jpg',
    date: '5 mins ago',
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: '/assets/art-post.jpg',
    date: '15 mins ago',
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: 'Every moment is a fresh beginning.',
    photo: '/assets/carpe-diem.jpg',
    date: '1 hour ago',
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: '/assets/developer.jpg',
    date: '4 hours ago',
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: '/assets/music.jpg',
    date: '5 hours ago',
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: '/assets/jdm.jpg',
    date: '1 day ago',
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: 'Never regret anything that made you smile.',
    photo: '/assets/hapyness.jpg',
    date: '2 days ago',
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: '/assets/journey.jpg',
    date: '3 days ago',
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: 'Change the world by being yourself.',
    photo: '/assets/self-loving.jpg',
    date: '5 days ago',
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: '/assets/meditation.jpg',
    date: '1 week ago',
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 11,
    photo: '/assets/eyes.jpg',
    date: '1 week ago',
    userId: 4,
    like: 104,
    comment: 12,
  },
  {
    id: 12,
    photo: '/assets/guitar.jpg',
    date: '1 week ago',
    userId: 4,
    like: 104,
    comment: 12,
  },
  {
    id: 13,
    desc: 'this is text post',
    date: '1 week ago',
    userId: 4,
    like: 104,
    comment: 12,
  },
  {
    id: 14,
    photo: '/assets/jazz.jpg',
    date: '1 week ago',
    userId: 4,
    like: 104,
    comment: 12,
  },
  {
    id: 15,
    desc: 'this is text post even',
    date: '1 week ago',
    userId: 4,
    like: 104,
    comment: 12,
  },
];
